security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #curl风格
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true  #在eureka中显示ip
logging:
  level:
    root: INFO
